// <auto-generated />
using Ebooks.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ebooks.Data.Migrations
{
    [DbContext(typeof(EbooksContext))]
    [Migration("20210103174913_EbookPage")]
    partial class EbookPage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Ebooks.Core.Domain.Ebook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ebooks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Peter Himschoot",
                            Description = "Build web applications in C# and Microsoft .NET that run in any modern browser. This second edition is updated to work with the release version of Blazor and covers Blazor’s use in creating both server-side and WebAssembly Blazor applications",
                            Name = "Microsoft Blazor: Building Web Applications in .NET"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Michele Aponte",
                            Description = "Attention .NET developers who no longer want to use JavaScript for your front end. Quickly and efficiently learn how to use C# for your single-page application (SPA) thanks to Blazor",
                            Name = "Building Single Page Applications in .NET Core 3: Jumpstart Coding Using Blazor and C#"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Adam Freeman",
                            Description = "Now in its 8th edition, Pro ASP.NET Core has been thoroughly updated for ASP.NET Core 3 and online for ASP.NET Core 5 and .NET 5.0. This comprehensive, full-color guide is the only book you need to learn ASP.NET Core development.",
                            Name = "Pro ASP.NET Core 3: Develop Cloud-Ready Web Applications Using MVC, Blazor, and Razor Pages"
                        });
                });

            modelBuilder.Entity("Ebooks.Core.Domain.Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EbookId")
                        .HasColumnType("int");

                    b.Property<int>("PageNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EbookId");

                    b.ToTable("Pages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean faucibus condimentum est ut vehicula. Fusce ornare, purus nec auctor malesuada, enim est porttitor justo, sed eleifend orci urna sed enim. Mauris volutpat enim sem, at aliquam libero interdum eget. Donec luctus nisl a mollis placerat. Nam scelerisque magna vel leo auctor, a dapibus ipsum eleifend. Nunc sodales bibendum consequat. Vivamus efficitur risus ac lacus elementum, sit amet condimentum tellus aliquet. In et mi ac nunc bibendum tincidunt sed a orci. Donec vel tortor et magna luctus laoreet ut et urna. Aliquam eu nulla efficitur, cursus enim gravida, rutrum diam. Morbi feugiat neque ac convallis auctor. Suspendisse magna arcu, rhoncus id dolor in, ullamcorper hendrerit velit. Curabitur tincidunt dui eget commodo elementum. Sed eu eleifend mauris. Donec non nisi eros.Aliquam erat arcu, tincidunt sodales tortor vel, lobortis fringilla nibh. Etiam eu tortor et magna ultricies suscipit. Cras scelerisque lorem nec nisl accumsan, in sagittis orci viverra. Ut sit amet urna urna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin interdum augue at sapien viverra, sed cursus mauris dignissim. Aliquam erat volutpat. Aliquam sed massa sem. Donec id tempor odio, non hendrerit eros. Donec imperdiet eros non dignissim ornare. Aliquam vitae semper metus. Nunc eget dui nulla. Nulla facilisi.",
                            EbookId = 1,
                            PageNo = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Phasellus luctus interdum massa at auctor. Praesent fermentum ipsum sit amet pulvinar tristique. Nullam venenatis et neque vitae iaculis. Donec ligula ex, vestibulum laoreet ipsum ut, consectetur cursus ex. Quisque molestie vulputate purus, in luctus nisi. Aliquam consequat, nulla quis tincidunt elementum, nunc felis convallis quam, in consectetur lacus elit ac dui. Quisque posuere tortor sed convallis rutrum. Nunc congue risus et ipsum convallis interdum. Sed ac bibendum nisl. Vestibulum molestie ut odio vel suscipit. Sed semper ac lacus in mollis. Ut non lacus arcu.",
                            EbookId = 1,
                            PageNo = 2
                        },
                        new
                        {
                            Id = 3,
                            Content = "Sed scelerisque scelerisque consequat. Curabitur placerat faucibus sem a luctus. Pellentesque malesuada aliquam scelerisque. Cras blandit ullamcorper est, eget tempus quam consectetur non. Suspendisse maximus gravida velit, eget ultricies nulla egestas vel. Mauris non scelerisque nibh. Sed dictum augue nibh, vitae mollis felis pharetra ac. Nam efficitur libero id urna commodo, sed bibendum lacus vulputate. Duis vitae dui laoreet, tincidunt turpis sed, bibendum erat. Donec rhoncus eget erat id viverra. Pellentesque dolor justo, faucibus ut lorem vitae, pulvinar varius libero. Nulla bibendum egestas lorem, ut lacinia diam tincidunt a. Vivamus eu justo at tellus tempus hendrerit id suscipit mi. Duis porttitor mauris et faucibus tempus.",
                            EbookId = 2,
                            PageNo = 1
                        });
                });

            modelBuilder.Entity("Ebooks.Core.Domain.Page", b =>
                {
                    b.HasOne("Ebooks.Core.Domain.Ebook", "Ebook")
                        .WithMany("Pages")
                        .HasForeignKey("EbookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ebook");
                });

            modelBuilder.Entity("Ebooks.Core.Domain.Ebook", b =>
                {
                    b.Navigation("Pages");
                });
#pragma warning restore 612, 618
        }
    }
}
